// @flow
'use strict';

export const SHOW_NEW_DIALOG = 'SHOW_NEW_DIALOG';
export const HIDE_NEW_DIALOG = 'HIDE_NEW_DIALOG';

export const SAVE_PROJECT_REQUEST = 'SAVE_PROJECT_REQUEST';
export const SAVE_PROJECT_SUCCESS = 'SAVE_PROJECT_SUCCESS';
export const SAVE_PROJECT_ERROR = 'SAVE_PROJECT_ERROR'; 